name: Generate index.html and create PR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pandas geopy folium
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run index.py to generate index.html
      run: |
        python index.py

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      id: cpr
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Update index.html'
        branch: update-index-html
        title: 'Update index.html'
        body: 'This PR updates the index.html file.'
        labels: auto-merge

    - name: Enable auto-merge
      if: steps.cpr.outputs.pull-request-number
      run: |
        gh pr merge --auto --merge --delete-branch "${{ steps.cpr.outputs.pull-request-number }}"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}