name: Generate index.html and create PR

on:
  push:
    branches:
      - main  # Adjust this if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pandas geopy folium
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run index.py to generate index.html
      run: |
        python index.py

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add index.html
        git commit -m 'Update index.html'

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Update index.html'
        branch: update-index-html
        title: 'Update index.html'
        body: 'This PR updates the index.html file.'
        labels: 'auto-merge'

    - name: Auto-merge Pull Request
      uses: actions/github-script@v6
      with:
        script: |
          const { data: pullRequests } = await github.pulls.list({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'open',
            head: 'update-index-html'
          });

          if (pullRequests.length > 0) {
            const pullRequest = pullRequests[0];
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pullRequest.number,
              merge_method: 'squash'
            });
          }